# Generated by Django 3.1.1 on 2020-09-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='image2',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='images',
            name='image3',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
