# Generated by Django 2.0.2 on 2020-09-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='summary',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
